//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessControl.Resources_Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificacionesEspañol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificacionesEspañol() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessControl.Resources_Language.NotificacionesEspañol", typeof(NotificacionesEspañol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        internal static string Encabezado1 {
            get {
                return ResourceManager.GetString("Encabezado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Completado.
        /// </summary>
        internal static string EncabezadoConexion1 {
            get {
                return ResourceManager.GetString("EncabezadoConexion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR 03.
        /// </summary>
        internal static string EncabezadoConexion2 {
            get {
                return ResourceManager.GetString("EncabezadoConexion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string EncabezadoLogOut {
            get {
                return ResourceManager.GetString("EncabezadoLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas seguro de cerrar la aplicacion?.
        /// </summary>
        internal static string Mensaje1 {
            get {
                return ResourceManager.GetString("Mensaje1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexion Exitosa.
        /// </summary>
        internal static string MensajeConexion1 {
            get {
                return ResourceManager.GetString("MensajeConexion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar conectar.
        /// </summary>
        internal static string MensajeConexion2 {
            get {
                return ResourceManager.GetString("MensajeConexion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas seguro de salir de la sesion?.
        /// </summary>
        internal static string MensajeLogOut {
            get {
                return ResourceManager.GetString("MensajeLogOut", resourceCulture);
            }
        }
    }
}
